
# attempt to configure Travis-CI to 
# install Python and test under macOS

language: python

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON=3.5.1

before_install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew install openssl readline
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi

install: 
 - python setup.py install 

script: py.test --assert=plain
